### ISSUE TITLE
License of this repo

### ISSUE THREAD

**Issue by leocd91** [zhongpenggeo/MT2DFD#2]
Hi,

Great work on this notebooks.

What is the license of this repository, is it MIT?

I would like to make an open tutorial about deep learning based on the data generated from your notebook.

Thank you.

**Comment by zhongpenggeo** [comment]
> Hi,
> 
> Great work on this notebooks.
> 
> What is the license of this repository, is it MIT?
> 
> I would like to make an open tutorial about deep learning based on the data generated from your notebook.
> 
> Thank you.

yes, it is MIT license.
